### ISSUE TITLE
Evolutionary.jl

### ISSUE THREAD

**Issue by giulib3** [wildart/wildart.github.io#3]
Hi @wildart, I am working with Evolutionary.jl, in particular with GA. Could you please indicate me where I can find documentation on setting bounds for GA algorithms? I am getting some trouble is setting them. Thank you

**Comment by wildart** [comment]
There is no proper documentation yet. See an example, https://github.com/wildart/Evolutionary.jl/blob/master/examples/beam.jl, of how to specify the constraints. Please, open [the issue in the package repo](https://github.com/wildart/Evolutionary.jl/issues) to continue this discussion.
